### ISSUE TITLE
Create project file structure

### ISSUE THREAD

**Issue by Overflow922** [Galaxy13/telegram_bot-Docker.test#1]
We should come up with basic project file structure. I can think of these directories for now:
1. Source - contains source files
2. Test - tests
3. Configs - directory for configs (e.g. telegram bot token). I suppose we can use json files as a template of our config files.

**Comment by Galaxy13** [comment]
1. Why do we need 'source' folder? Is everything is already soucre code?
2. Test - agree, there is need to be 2 scipts, testing part of Telegram Api, and other to test behaviour of QR script
3. Json for config - as a template and tests.

**Comment by Overflow922** [comment]
1. Since we are not expecting too many files - we can keep them in the root.
3. What are the benefits of ini file comparing to json?
