### ISSUE TITLE
Update #1 (tests and Telegram API)

### ISSUE THREAD

**Issue by Galaxy13** [Galaxy13/telegram_bot-Docker.test#2]
The main goal for now is testing of functions, creating QR-code and build an intercation between functions, that create a QR-code, and end-point Telegram Bot.

**Comment by Overflow922** [comment]
It is an issue, in essence, that name should reflect what should be done. I don't see the goal for this issue. Could you please edit the name and description to single out what should be done (e.g. integrate the application with telegram bot endpoint).

**Comment by Overflow922** [comment]
Closing this, since it was addressed in #3
